package pt.isel.ipw.http.errors

enum class ErrorCode {
    INTERNAL_ERROR,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    INSECURE_PASSWORD,
    INVALID_CREDENTIALS,
    INVALID_ROLE,
    INVALID_ROLES,
    INVALID_TOKEN,
    REFRESH_NOT_FOUND,
    LOGIN_EXPIRED,
    ACCESS_EXPIRED,
    REFRESH_EXPIRED,
    AREA_REQUIRED,
    AREA_NOT_FOUND,
    AREA_ALREADY_HAS_SUPERVISOR,
    INVALID_OFFSET,
    INVALID_LIMIT,
    PROCESS_NOT_FOUND
}