export const STATES = {
  NOT_ASSIGNED: "NOT_ASSIGNED",
  ASSIGNED: "ASSIGNED",
  ON_GOING: "ON_GOING",
  WAITING_APPROVAL_SUPERVISOR: "WAITING_APPROVAL_SUPERVISOR",
  APPROVED_BY_SUPERVISOR: "APPROVED_BY_SUPERVISOR",
  REJECTED_BY_SUPERVISOR: "REJECTED_BY_SUPERVISOR",
  WAITING_APPROVAL_MANAGER: "WAITING_APPROVAL_MANAGER",
  APPROVED_BY_MANAGER: "APPROVED_BY_MANAGER",
  REJECTED_BY_MANAGER: "REJECTED_BY_MANAGER",
  CANCELED: "CANCELED",
  NOT_STARTED: "NOT_STARTED",
  REJECTED: "REJECTED",
} as const;

export type ProcessState = (typeof STATES)[keyof typeof STATES];
