import type { ProcessResponse } from "../Utility/Api/ProcessApi";

export const mockProcessResponse: ProcessResponse = {
  id: 101,
  name: "Insurance Claim Investigation",
  location: {
    id: 12,
    district: "Lisbon",
    county: "Lisbon",
    street: "Rua da Liberdade 123",
    latitude: "nul",
    longitude: "-9.1393",
  },
  creationDate: "2026-04-11T09:30:00Z",
  dueDate: "2026-04-25T18:00:00Z",
  priority: 2,
  area: "Auto",
  typification: "Suspicious Claim",
  triator: {
    id: 1,
    name: "Maria Silva",
    email: "maria.silva@company.com",
    areaId: 10,
    roles: ["TRIATOR"],
  },
  investigator: {
    id: 2,
    name: "Joao Costa",
    email: "joao.costa@company.com",
    areaId: 10,
    roles: ["INVESTIGATOR"],
  },
  supervisor: {
    id: 3,
    name: "Ana Ribeiro",
    email: "ana.ribeiro@company.com",
    areaId: 10,
    roles: ["SUPERVISOR"],
  },
  state: "IN_PROGRESS",
  proves: {
    id: 501,
    processId: 101,
    fileName: "photo_front_bumper.jpg",
    fileType: "image/jpeg",
    fileUrl: "https://example.com/files/photo_front_bumper.jpg",
    createdAt: "2026-04-11T10:00:00Z",
  },
  report: {
    id: 601,
    processId: 101,
    content: "Initial analysis indicates potential inconsistencies in the claim timeline.",
    createdAt: "2026-04-11T11:00:00Z",
    updatedAt: "2026-04-11T11:30:00Z",
  },
  notes: {
    id: 701,
    processId: 101,
    proves: null,
    content: "Customer requested fast-track handling.",
    authorId: 2,
    createdAt: "2026-04-11T12:00:00Z",
  },
  activity: {
    id: 801,
    processId: 101,
    userId: 1,
    action: "ASSIGNED_INVESTIGATOR",
    description: "Process assigned to investigator Joao Costa.",
    createdAt: "2026-04-11T09:45:00Z",
  },
};