spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


app.jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
app.jwt.login-token-ttl-minutes=5
app.jwt.access-token-ttl-minutes=120
app.jwt.refresh-token-ttl-minutes=10080

minio.internal-endpoint=http://localhost:9000
minio.public-endpoint=http://localhost:9000
minio.access-key=ipw
minio.secret-key=ipw-password
minio.bucket=process-attachments
