package pt.isel.ipw.domain

enum class ActivityActions {
    CREATED_PROCESS,
    ASSIGNED_SUPERVISOR,
    UPDATED_REPORT,
    CANCELLED_PROCESS,
    CHANGED_PRIORITY,
    CHANGED_END_DATE,
    CREATED_REPORT,
    DELETED_REPORT,
    APPROVED_REPORT_SUPERVISOR,
    REJECTED_REPORT_SUPERVISOR,
    APPROVED_REPORT_MANAGER,
    REJECTED_REPORT_MANAGER,
    SUBMIT_PROCESS_FOR_APPROVAL
}


fun ActivityActions.mapToString(): String =
    when (this) {
        ActivityActions.CREATED_PROCESS -> "CREATED_PROCESS"
        ActivityActions.UPDATED_REPORT -> "UPDATED_REPORT"
        ActivityActions.CANCELLED_PROCESS -> "CANCELLED_PROCESS"
        ActivityActions.CHANGED_PRIORITY -> "CHANGED_PRIORITY"
        ActivityActions.ASSIGNED_SUPERVISOR -> "ASSIGNED_SUPERVISOR"
        ActivityActions.CHANGED_END_DATE -> "CHANGED_END_DATE"
        ActivityActions.CREATED_REPORT -> "CREATED_REPORT"
        ActivityActions.DELETED_REPORT -> "DELETED_REPORT"
        ActivityActions.APPROVED_REPORT_SUPERVISOR -> "APPROVED_SUPERVISOR"
        ActivityActions.REJECTED_REPORT_SUPERVISOR -> "REJECTED_SUPERVISOR"
        ActivityActions.APPROVED_REPORT_MANAGER -> "APPROVED_REPORT_MANAGER"
        ActivityActions.REJECTED_REPORT_MANAGER -> "REJECTED_REPORT_MANAGER"
        ActivityActions.SUBMIT_PROCESS_FOR_APPROVAL -> "SUBMIT_PROCESS_FOR_APPROVAL"
    }






