export const Icon = {
    AccountCircle: "account_circle",
    Lock: "lock",
    Crown: "crown",
    Shield: "shield",
    Star: "star",
    Search: "search",
    Group: "group",
    Visibility: "visibility",
    Location: "location_on",
    Calendar: "calendar_today",
    Success: "check_circle",
    Error: "cancel",
    Info: "info",
    Warning: "warning",
    ArrowForward: "arrow_forward",
    ArrowBack: "arrow_back",
    Check: "check",
    Circle: "circle",
    Clock: "schedule",
    CarCrash: "car_crash",
    History: "history",
    Email: "mail",
}