@baseUrl = http://localhost:8080/api

@loginTokenInvestigator =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlcyI6WyJpbnZlc3RpZ2F0b3IiXSwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzgyNTAxMDIxLCJleHAiOjE3ODI1MDEzMjF9.iVL1FxXSgrk2PFWOGoQ4vPueX2TSTyF8dD2UEcTfocILeTtGVn3cgQegbk3cKcRFy06M204Eqxmi6rHf4gnY4A
@accessTokenInvestigator =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlIjoiaW52ZXN0aWdhdG9yIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4MjUwMTA1MSwiZXhwIjoxNzgyNTA4MjUxfQ.H61mvuNFXqYpgipK5nATwYEElQ2RU61Ib1IqMciOsq7gGzF3mBjmww53bijqtO5gyHwNcL2bs8UVcJT4kBdEbA

@processId = 1

@noteId = 1
@proveId = 1

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}


### Create Note - Investigator
POST {{baseUrl}}/process/{{processId}}/note
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
    "processId": {{processId}},
    "content": "This is a note for the process 5."
}


### Get Notes By Process Id - Investigator
GET {{baseUrl}}/process/{{processId}}/note
Authorization: Bearer {{accessTokenInvestigator}}


### Get Notes By Process Id - Investigator
GET {{baseUrl}}/process/{{processId}}/proves/{{proveId}}/note
Authorization: Bearer {{accessTokenInvestigator}}


### Update Note
PATCH {{baseUrl}}/process/{{processId}}/note/{{noteId}}
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "content": "UPDATED!!!"
}

