@baseUrl = http://localhost:8080/api

@loginTokenInvestigator =
@accessTokenInvestigator =

@processId = 1

@noteId = 1
@proveId = 1

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}


### Create Note - Investigator
POST {{baseUrl}}/process/{{processId}}/note
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
    "processId": {{processId}},
    "content": "This is a note for the process 5."
}


### Get Notes By Process Id - Investigator
GET {{baseUrl}}/process/{{processId}}/note
Authorization: Bearer {{accessTokenInvestigator}}


