@baseUrl = http://localhost:8080/api
@loginToken =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlcyI6WyJpbnZlc3RpZ2F0b3IiXSwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzgzMDA5OTAyLCJleHAiOjE3ODMwMTAyMDJ9.UiHfz5L-8-rAO3N4r-3uqkLEqesmNAyNxCUHiQ15lspGOolR6kio8kCsokadxi_0vHIVNlhE2xY8a24ZhtVtgA


@accessTokenTriator  = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwidXNlcklkIjoxLCJyb2xlIjoidHJpYXRvciIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODI5OTk2NTgsImV4cCI6MTc4MzAwNjg1OH0.F3sucumUih1b2YQktNKt9BHMoUXVEZcyovNobEiPCiYFdBeSpEuc8G_ytYxk5nx_e_gNS6yBfLTc9031nlMnvg
@refreshTokenTriator =

@accessTokenInvestigator  =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlIjoiaW52ZXN0aWdhdG9yIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4MzAwOTkyOSwiZXhwIjoxNzgzMDE3MTI5fQ.GQhshatBSvAOjiqOqYhXSMblNtj1Y52ok0wIPEIITt1rA1D3oPIGZS8pxmktiUJi96TFtk7C7vWo7SjcjdCr5A

@refreshTokenInvestigator =

@accessTokenSupervisor  =
@refreshTokenSupervisor =


### Create User - Triador
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Chico Triator",
  "email": "chicoT@gmail.com",
  "password": "12345",
  "areaId": null,
  "roles": ["triator"]
}

### Create User - Supervisor
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Chico Supervisor",
  "email": "chicoS@gmail.com",
  "password": "12345",
  "areaId": 4,
  "roles": ["supervisor"]
}

### Create User - Investigator
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Chico Investigator",
  "email": "chicoI@gmail.com",
  "password": "12345",
  "areaId": 2,
  "roles": ["investigator"]
}

### Login - Triator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "tiago@ipw.pt",
  "password": "12345"
}

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Login - Supervisor
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "carol@ipw.pt",
  "password": "12345"
}


### Select Role - usar loginToken no Authorization header
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
  "role": "triator"
}

### Select Role - usar loginToken no Authorization header
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
  "role": "investigator"
}

### Select Role - usar loginToken no Authorization header
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
  "role": "supervisor"
}

### Create Process - triator
POST {{baseUrl}}/process
Content-Type: application/json
Authorization: Bearer {{accessTokenTriator}}

{
  "name": "Processo Teste 6",
  "street": "Rua Augusta 1",
  "county": "Lisboa",
  "district": "Lisboa",
  "latitude": null,
  "longitude": null,
  "area": "Car Accident",
  "priority": "normal",
  "expiresAt": "2026-12-31T23:59:59",
  "investigatorId": 2,
  "supervisorId": 3,
  "canBeFraud": false,
  "insuranceId": null,
  "typificationId": null,
  "note": "Nota inicial do processo"
}





### Get by id processes - Investigator
GET {{baseUrl}}/process/1
Authorization: Bearer {{accessTokenInvestigator}}



### Get All Processes - investigator (sem filtros)
GET {{baseUrl}}/process?offset=0&limit=2&state=assigned
Authorization: Bearer {{accessTokenInvestigator}}

### Get All Processes - supervisor (com paginação)
GET {{baseUrl}}/process?offset=5&limit=5
Authorization: Bearer {{accessTokenSupervisor}}

### Get All Processes - investigator (filtrar por área)
GET {{baseUrl}}/process?offset=0&limit=2&area_id=1
Authorization: Bearer {{accessTokenInvestigator}}

### Get Activities by Process - investigator (sem filtros)
GET {{baseUrl}}/activity/process/12
Authorization: Bearer {{accessTokenInvestigator}}

### Get Activities by Process - investigator (com paginação)
GET {{baseUrl}}/activity/process/1?offset=0&limit=5
Authorization: Bearer {{accessTokenInvestigator}}

