@baseUrl = http://localhost:8080/api
@loginToken =

@loginTokenTriator =
@loginTokenInvestigator =
@loginTokenSupervisor =

@accessTokenTriator  =
@refreshTokenTriator =

@accessTokenInvestigator  =

@refreshTokenInvestigator =

@accessTokenSupervisor  =
@refreshTokenSupervisor =

### Login - Triator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "tiago@ipw.pt",
  "password": "12345"
}

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Login - Supervisor
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "sofia@ipw.pt",
  "password": "12345"
}


### Select Role - Triator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenTriator}}

{
  "role": "triator"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}

### Select Role - Supervisor
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenSupervisor}}

{
  "role": "supervisor"
}

### Create Process - triator
POST {{baseUrl}}/process
Content-Type: application/json
Authorization: Bearer {{accessTokenTriator}}

{
  "name": "Processo Teste 6",
  "street": "Rua Augusta 1",
  "county": "Lisboa",
  "district": "Lisboa",
  "latitude": null,
  "longitude": null,
  "area": "Car Accident",
  "priority": "normal",
  "expiresAt": "2026-12-31T23:59:59",
  "investigatorId": 2,
  "supervisorId": 3,
  "canBeFraud": false,
  "insuranceId": null,
  "typificationId": null,
  "note": "Nota inicial do processo"
}

### Get by id processes - Investigator
GET {{baseUrl}}/process/1
Authorization: Bearer {{accessTokenInvestigator}}

### Get All Processes - investigator (sem filtros)
GET {{baseUrl}}/process
Authorization: Bearer {{accessTokenInvestigator}}

### Get All Processes - supervisor (com paginação)
GET {{baseUrl}}/process?offset=5&limit=5
Authorization: Bearer {{accessTokenInvestigator}}

### Get All Processes - investigator (filtrar por área)
GET {{baseUrl}}/process?offset=0&limit=2&area_id=1
Authorization: Bearer {{accessTokenInvestigator}}

### Get Activities by Process - investigator (sem filtros)
GET {{baseUrl}}/activity/process/12
Authorization: Bearer {{accessTokenInvestigator}}

