@baseUrl = http://localhost:8080/api

@loginTokenInvestigator =
@accessTokenInvestigator =
@processId = 1

# Ficheiro local usado no PUT para o MinIO.
@fileName = Logo.png
@contentType = image/png
@fileSize = 38500

@uploadUrl =
@storageKey =

@proveId = 1

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}

### Create upload URL
POST {{baseUrl}}/process/{{processId}}/proves/upload-url
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "fileName": "{{fileName}}",
  "contentType": "{{contentType}}",
  "fileSize": {{fileSize}}
}

### Upload file bytes to MinIO
PUT {{uploadUrl}}
Content-Type: {{contentType}}

< C:\Logo.png

### Create prove metadata
POST {{baseUrl}}/process/{{processId}}/proves
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "fileName": "{{fileName}}",
  "contentType": "{{contentType}}",
  "fileSize": {{fileSize}},
  "storageKey": "{{storageKey}}"
}

### Get process proves metadata
GET {{baseUrl}}/process/{{processId}}/proves
Authorization: Bearer {{accessTokenInvestigator}}

### Get prove access URL
GET {{baseUrl}}/process/{{processId}}/proves/{{proveId}}/url
Authorization: Bearer {{accessTokenInvestigator}}

### Delete prove
DELETE {{baseUrl}}/process/{{processId}}/proves/{{proveId}}
Authorization: Bearer {{accessTokenInvestigator}}
