@baseUrl = http://localhost:8080/api

@loginTokenInvestigator =
@accessTokenInvestigator =
@processId = 1

# Ficheiro local usado no PUT para o MinIO.
@fileName = Logo.png
@contentType = image/png
@fileSize = 38500

@uploadUrl =http://localhost:9000/process-attachments/processes/1/d852c722-053a-49d2-a69c-b1cc802c03e4-Logo.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ipw%2F20260618%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260618T175441Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=4b5852c9ee07a9794228b28a954f177a3e4946b67e1be4dd39dd7fd5757f61f1
@storageKey = processes/1/d852c722-053a-49d2-a69c-b1cc802c03e4-Logo.png

@proveId = 1

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}

### Create upload URL
POST {{baseUrl}}/process/{{processId}}/proves/upload-url
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "fileName": "{{fileName}}",
  "contentType": "{{contentType}}",
  "fileSize": {{fileSize}}
}

### Upload file bytes to MinIO
PUT {{uploadUrl}}
Content-Type: {{contentType}}

< C:\Logo.png

### Create prove metadata
POST {{baseUrl}}/process/{{processId}}/proves
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "fileName": "{{fileName}}",
  "contentType": "{{contentType}}",
  "fileSize": {{fileSize}},
  "storageKey": "{{storageKey}}"
}

### Get process proves metadata
GET {{baseUrl}}/process/{{processId}}/proves
Authorization: Bearer {{accessTokenInvestigator}}

### Get prove access URL
GET {{baseUrl}}/process/{{processId}}/proves/{{proveId}}/url
Authorization: Bearer {{accessTokenInvestigator}}

### Delete prove
DELETE {{baseUrl}}/process/{{processId}}/proves/{{proveId}}
Authorization: Bearer {{accessTokenInvestigator}}
