@baseUrl = http://localhost:8080/api

@loginTokenTriator =

@loginTokenInvestigator =

@loginTokenSupervisor =

@loginTokenManager =

@accessTokenTriator =

@accessTokenInvestigator =

@accessTokenSupervisor =

@accessTokenManager =

@processId = 1

@reportId = 1


### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Login - Supervisor
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "sofia@ipw.pt",
  "password": "12345"
}

### Login - Manager
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "gabriel@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}


### Select Role - Supervisor
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenSupervisor}}

{
  "role": "supervisor"
}

### Select Role - Manager
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenManager}}

{
  "role": "manager"
}

### Criar relatório
POST {{baseUrl}}/process/{{processId}}/report
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "content": "Veiculo com danos frontais compativeis com embate em objeto fixo. Foram recolhidas fotografias do local e do veiculo."
}

### Buscar relatório - Investigator
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenInvestigator}}

### Buscar relatório - Supervisor
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenSupervisor}}

### Buscar relatório - Manager
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenManager}}

### Sumeter processo para aprovação - Investigator
POST {{baseUrl}}/process/{{processId}}/submit
Authorization: Bearer {{accessTokenInvestigator}}

### Atualizar relatório
PATCH {{baseUrl}}/process/{{processId}}/report
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "content": "Relatorio atualizado com informacoes adicionais apos inspecao no local."
}

### Aprovar relatório - Supervisor
POST {{baseUrl}}/process/{{processId}}/report/approve
Authorization: Bearer {{accessTokenSupervisor}}

### Aprovar relatório - Manager
POST {{baseUrl}}/process/{{processId}}/report/approve
Authorization: Bearer {{accessTokenManager}}
