@baseUrl = http://localhost:8080/api

@loginTokenInvestigator = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlcyI6WyJpbnZlc3RpZ2F0b3IiXSwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzgzNjkyNDAwLCJleHAiOjE3ODM2OTI3MDB9.QuFdD-zK2H1JpzDPxg3HvYibss9oT4XdZeEsogWPQOFaaDR5FG5Xaio-UYrduNhoudXiSaN8qEspztS5jDv9Qg
@loginTokenSupervisor   = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwidXNlcklkIjozLCJyb2xlcyI6WyJzdXBlcnZpc29yIl0sInR5cGUiOiJsb2dpbiIsImlhdCI6MTc4MzY5MjQxNCwiZXhwIjoxNzgzNjkyNzE0fQ.NeRyBxkcE_tfvsQi3Z7w1kQ_hX28PDTpUPPiLacuhH6XmUgE5j5_fGkB7g9-AJeMInWCXcgGjvwh9U4D1Lrg4A
@loginTokenManager      = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0IiwidXNlcklkIjo0LCJyb2xlcyI6WyJtYW5hZ2VyIl0sInR5cGUiOiJsb2dpbiIsImlhdCI6MTc4MzY5MjU1NCwiZXhwIjoxNzgzNjkyODU0fQ.Ay1viayuSo6yuKKZm8KqoJhq-5qFl74ZZLSQ7m8d_TLnIdf2cTawRy-8CWPaH_U1oQVjb0ku5nk8ey2VdSpFXw

@accessTokenInvestigator = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidXNlcklkIjoyLCJyb2xlIjoiaW52ZXN0aWdhdG9yIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc4MzY5MjU3MSwiZXhwIjoxNzgzNjk5NzcxfQ.EiKu_i53u-XpPYvDkGdgavSmB8CQwSHM8OKwsk6M05yirvHF3e9ajgZQEoi_9KtfdetuXdWYINiKO9tkq2hEVA
@accessTokenSupervisor   = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwidXNlcklkIjozLCJyb2xlIjoic3VwZXJ2aXNvciIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODM2OTI2NjUsImV4cCI6MTc4MzY5OTg2NX0.6nV1mDLSdpVIQ4IB13GYa5Kq1N_sr4Z0pFD4Awq6i7uTD8NeN5jGGRPGsBLB10VtmENwqlvbrqQUioMShQuCjw
@accessTokenManager      = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0IiwidXNlcklkIjo0LCJyb2xlIjoibWFuYWdlciIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODM2OTI2MDQsImV4cCI6MTc4MzY5OTgwNH0.D9Gmt7n9eTN_xzar3EqzX4NRvMN7O37Ri33OMX_pCIJ5fLGOZ86ws9RSLvBZ8E9hBY4Yko4wFQv7MO0kRaHOJg

@processId = 1
@reportId  = 1

### Login - Investigator
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "ana@ipw.pt",
  "password": "12345"
}

### Login - Supervisor
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "sofia@ipw.pt",
  "password": "12345"
}

### Login - Manager
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "gabriel@ipw.pt",
  "password": "12345"
}

### Select Role - Investigator
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenInvestigator}}

{
  "role": "investigator"
}


### Select Role - Supervisor
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenSupervisor}}

{
  "role": "supervisor"
}

### Select Role - Manager
POST {{baseUrl}}/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginTokenManager}}

{
  "role": "manager"
}

### Criar relatório
POST {{baseUrl}}/process/{{processId}}/report
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "content": "Veiculo com danos frontais compativeis com embate em objeto fixo. Foram recolhidas fotografias do local e do veiculo."
}

### Buscar relatório - Investigator
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenInvestigator}}

### Buscar relatório - Supervisor
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenSupervisor}}

### Buscar relatório - Manager
GET {{baseUrl}}/process/{{processId}}/report
Authorization: Bearer {{accessTokenManager}}

### Sumeter processo para aprovação - Investigator
POST {{baseUrl}}/process/{{processId}}/submit
Authorization: Bearer {{accessTokenInvestigator}}

### Atualizar relatório
PATCH {{baseUrl}}/process/{{processId}}/report
Content-Type: application/json
Authorization: Bearer {{accessTokenInvestigator}}

{
  "content": "Relatorio atualizado com informacoes adicionais apos inspecao no local."
}

### Aprovar relatório - Supervisor
POST {{baseUrl}}/process/{{processId}}/report/approve
Authorization: Bearer {{accessTokenSupervisor}}

### Aprovar relatório - Manager
POST {{baseUrl}}/process/{{processId}}/report/approve
Authorization: Bearer {{accessTokenManager}}
