@baseUrl = http://localhost:8080
@loginToken =
@accessToken =
@refreshToken =

### Create User
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "Sarabuga",
  "email": "sarabuga@gmail.com",
  "password": "12345",
  "areaId": null,
  "roles": ["triator"]
}

### Login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "sarabuga@gmail.com",
  "password": "anime"
}

### Select Role
POST {{baseUrl}}/api/users/auth/select-role
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
  "role": "admin"
}

### Refresh Access Token
POST {{baseUrl}}/api/users/refresh-token
Authorization: Bearer {{refreshToken}}

### Get Roles
GET {{baseUrl}}/api/users/roles?email=chico@gmail.com

### Get All Users
GET {{baseUrl}}/api/users?offset=0&limit=10
Authorization: Bearer {{accessToken}}

### Protected endpoint example
GET {{baseUrl}}/api/history/6
Authorization: Bearer {{accessToken}}
